sudo: required

language: scala

services:
  - docker

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_install:
- docker run -d -p 9200:9200 -p 9300:9300 -e "path.repo=/tmp/elastic4s" -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.3.1

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

before_script:
- sudo chmod +x /usr/local/bin/sbt

scala:
- 2.12.8

script:
- sbt clean test

jdk:
- oraclejdk11

after_success: "./snapshot_deploy.sh"
