sudo: required

language: scala

services:
  - docker

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_install:
- docker-compose up -d

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

before_script:
- sudo chmod +x /usr/local/bin/sbt

scala:
- 2.12.8

script:
- sbt clean test

jdk:
- oraclejdk11

after_success: "./snapshot_deploy.sh"
