language: scala
before_script:
- ulimit -u 30000
scala:
- 2.11.7
- 2.10.5
script:
- sbt clean test
jdk:
- oraclejdk8
env:
  secure: N6nYcHF+gT+zMkSImnLzGADt3UfKHS2ihfClDLrwLbEqswS+MaOWUpIxgg/THeWlGMZ94oV0zK9OTOlZXcG7c4Af4BRzm8ydQqCCm4C+kCzvfDFpnSB4601VewHAD41Fx7GSxxANSs5IIE0Y6L0pns9zhGpfupkh9kXNySnT/uQ=
sudo: true